name: QA

on: [pull_request, workflow_dispatch]

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install dependencies
      run: |
        npm install
    - name: Run roboter
      run: |
        npx roboter qa